/* ============================================================
   Content data for Chana Design and Build
   ============================================================ */
const HOME = "Chana Construction.html";
const NAV_LINKS = [
  { label: "Home", href: HOME, page: "home" },
  { label: "About", href: "About.html", page: "about" },
  { label: "Services", href: "Services.html", page: "services" },
  { label: "Projects", href: "Projects.html", page: "projects" },
];

const ACCREDS = [
  "LABC", "NHBC", "10 Year Structural Warranty", "Considerate Constructors", "Federation of Master Builders",
];

const SERVICES = [
  {
    name: "Land & Property Acquisition",
    cap: "Site sourcing",
    desc: "With careful due diligence from day one we help clients identify and secure suitable land for new build developments, as well as properties for refurbishment, extension and redevelopment.",
  },
  {
    name: "Planning & Development Consultancy",
    cap: "Planning",
    desc: "Comprehensive support throughout the planning process — managing applications, approvals, and all associated documentation to bring your vision through committee and into reality.",
  },
  {
    name: "Architectural & Technical Services",
    cap: "Design & engineering",
    desc: "We work alongside our network of architects, structural engineers, and party-wall surveyors so every project is expertly planned and detailed from the outset.",
  },
  {
    name: "Interior Design & Visualisation",
    cap: "3D & interiors",
    desc: "Bespoke interior design including space planning, material selection, 3D visualisations, and immersive walkthroughs — so you experience your home before construction begins.",
  },
  {
    name: "Building Regulations & Quality Assurance",
    cap: "Compliance",
    desc: "We collaborate closely with local authorities and private building control to ensure all work complies with current regulations and is delivered to the highest industry standards.",
  },
  {
    name: "New Build Warranties",
    cap: "Peace of mind",
    desc: "Strong relationships with leading warranty providers give our clients confidence and protection throughout the construction process and for years beyond handover.",
  },
  {
    name: "Construction, Turnkey & Aftercare",
    cap: "Build & beyond",
    desc: "From groundwork to final handover we provide a fully managed turnkey service — and our commitment continues with dedicated post-build support long after the keys change hands.",
  },
];

const STATS = [
  { to: 100, suffix: "%", k: "Fixed, transparent pricing — no hidden costs, no surprises" },
  { to: 10, suffix: "yr", k: "Structural warranty on every new-build home we complete" },
  { to: 24, suffix: "h", k: "We respond to every enquiry within one working day" },
  { to: 0, suffix: "", k: "Corners cut — quality and transparency, without exception", display: "Zero" },
];

const PROJECTS = [
  { t: "Chigwell — Brook Way", s: "New Build · 6 bed · Chigwell · Essex", tag: "New Build", cls: "tall", label: "CHIGWELL — BROOK WAY",
    slug: "Chigwell-Brook-Way",
    img: "assets/Chigwell - Brook Way - Hero.png",
    video: "assets/Brookway Drone Video (1).mp4",
    duration: "12 months", year: "2024",
    brief: "A 4,500 sq ft six-bedroom, six-bathroom new-build family home in Chigwell — designed, planned and delivered turnkey from plot to handover.",
    challenge: "The project demanded a high level of finish across every room, with the client's brief calling for luxury materials, custom joinery and a cohesive interior scheme from ground floor to roof. Coordinating multiple specialist trades to a single quality standard required meticulous planning.",
    approach: "We assisted our client in finding the perfect plot and then helped design, obtain planning permission and build their dream home — managing every element in-house from the structural frame through to the final decoration.",
    outcome: "A beautifully finished 4,500 sq ft home handed over on time, backed by a 10-year LABC warranty. Every room delivered to the client's specification, with bespoke fitted furniture, premium tiling and a refined finish that has set a new benchmark for the street.",
    scope: ["Plot sourcing & acquisition", "Design & planning", "New build construction", "Bespoke joinery", "Bathroom fit-out", "10-year LABC warranty"],
    gallery: [
      "assets/Chigwell - Brook Way - Hero.png",
      "assets/Chigwell - Brook Way - After 1.jpg",
      "assets/Chigwell - Brook Way - After 2.jpg",
      "assets/Chigwell - Brook Way - After 3.jpg",
      "assets/Chigwell - Brook Way - After 4.jpg",
      "assets/Chigwell - Brook Way - After 5.jpg",
      "assets/Chigwell - Brook Way - After 6.jpg",
      "assets/Chigwell - Brook Way - After 7.jpg",
      "assets/Chigwell - Brook Way - After 8.jpg",
      "assets/Chigwell - Brook Way - After 9.jpg",
      "assets/Chigwell - Brook Way - After 10.jpg",
      "assets/Chigwell - Brook Way - After 11.jpg",
      "assets/Chigwell - Brook Way - After 12.jpg",
      "assets/Chigwell - Brook Way - After 13.jpg",
      "assets/Chigwell - Brook Way - After 14.jpg",
      "assets/Chigwell - Brook Way - After 15.jpg",
      "assets/Chigwell - Brook Way - After 16.jpg",
      "assets/Chigwell - Brook Way - After 17.jpg",
      "assets/Chigwell - Brook Way - After 18.jpg",
      "assets/Chigwell - Brook Way - After 19.jpg",
      "assets/Chigwell - Brook Way - After 20.jpg",
    ],
    before: [
      "assets/Chigwell - Brook Way - Before 1.jpg",
      "assets/Chigwell - Brook Way - Before 2.jpg",
      "assets/Chigwell - Brook Way - Before 3.jpg",
      "assets/Chigwell - Brook Way - Before 4.jpg",
      "assets/Chigwell - Brook Way - Before 5.jpg",
      "assets/Chigwell - Brook Way - Before 6.jpg",
    ]
  },
  { t: "Chigwell — Chester Road", s: "New Build · 5 bed · Chigwell · Essex", tag: "New Build", cls: "wide", label: "CHIGWELL — CHESTER ROAD",
    slug: "Chigwell-House",
    img: "assets/Chigwell - Chester Road - Hero.png",
    imgContain: true, cardFull: true,
    duration: "12 months", year: "2024",
    brief: "A 3,000 sq ft five-bedroom, five-bathroom new-build family home in Chigwell — designed, planned and delivered turnkey from plot to handover.",
    challenge: "Delivering a 3,000 sq ft family home to an exacting specification required careful coordination across every trade, from the structural frame through to the bespoke fitted wardrobes and bathroom suites. The client had a clear vision for the interiors and expected every detail executed exactly as specified.",
    approach: "We assisted our client in finding the perfect plot and then helped design, obtain planning permission and build their dream home — managing structure, fit-out, plumbing, electrics and interior joinery with a single point of contact throughout.",
    outcome: "A 3,000 sq ft home handed over on programme, backed by a 10-year NHBC warranty. The clients moved in to a fully finished, furniture-ready house — from the master suite through to the wall-hung sanitaryware in all five bathrooms.",
    scope: ["Plot sourcing & acquisition", "Design & planning", "New build construction", "Bespoke fitted joinery", "Bathroom design & fit-out", "10-year NHBC warranty"],
    gallery: [
      "assets/Chigwell - Chester Road - Hero.png",
      "assets/Chigwell - Chester Road - After 1.jpg",
      "assets/Chigwell - Chester Road - After 2.jpg",
      "assets/Chigwell - Chester Road - After 3.jpg",
      "assets/Chigwell - Chester Road - After 4.jpg",
      "assets/Chigwell - Chester Road - After 5.jpg",
      "assets/Chigwell - Chester Road - After 6.jpg",
    ],
    before: [
      "assets/Chigwell - Chester Road - Before 1.jpg",
      "assets/Chigwell - Chester Road - Before 2.jpg",
      "assets/Chigwell - Chester Road - Before 3.jpg",
      "assets/Chigwell - Chester Road - Before 4.jpg",
      "assets/Chigwell - Chester Road - Before 5.jpg",
      "assets/Chigwell - Chester Road - Before 6.jpg",
    ]
  },
  { t: "Emerson Park — Nelmes Road", s: "New Build · 8 bed · Emerson Park · London", tag: "New Build", cls: "sqr", label: "EMERSON PARK — NELMES ROAD",
    slug: "Emerson-Park-Nelmes-Road",
    img: "assets/Emerson Park - Nelmes Road - Hero.png",
    imgContain: true,
    video: "assets/Nelmes Road.mp4", videoPortrait: true,
    duration: "16 months", year: "2024",
    brief: "An 11,000 sq ft eight-bedroom, eleven-bathroom new-build in Emerson Park, Hornchurch — designed, planned and delivered turnkey from plot to handover.",
    challenge: "Delivering a home of this scale to the highest specification demanded exceptional coordination across dozens of specialist trades simultaneously. Every decision — from the structural system to the finest interior detail — had to be managed to a single consistent standard across 11,000 sq ft of living space.",
    approach: "We assisted our client in finding the perfect plot and then helped design, obtain planning permission and build their dream home — overseeing every stage in-house from groundworks through to the finished interior.",
    outcome: "An 11,000 sq ft landmark home handed over on programme, backed by a 10-year Build Zone warranty. A turnkey delivery — the client moved into a fully finished, furniture-ready residence from day one.",
    scope: ["Plot sourcing & acquisition", "Design & planning", "New build construction", "Bespoke joinery & fit-out", "Bathroom & kitchen design", "10-year Build Zone warranty"],
    before: [
      "assets/Emerson Park - Nelmes Road - Before 1.jpg",
      "assets/Emerson Park - Nelmes Road - Before 2.jpg",
      "assets/Emerson Park - Nelmes Road - Before 3.jpg",
      "assets/Emerson Park - Nelmes Road - Before 4.jpg",
      "assets/Emerson Park - Nelmes Road - Before 5.jpg",
    ],
    gallery: [
      "assets/Emerson Park - Nelmes Road - After 1.jpg",
      "assets/Emerson Park - Nelmes Road - After 2.jpg",
      "assets/Emerson Park - Nelmes Road - After 3.jpg",
      "assets/Emerson Park - Nelmes Road - After 4.jpg",
      "assets/Emerson Park - Nelmes Road - After 5.jpg",
      "assets/Emerson Park - Nelmes Road - After 6.jpg",
      "assets/Emerson Park - Nelmes Road - After 7.jpg",
      "assets/Emerson Park - Nelmes Road - After 8.jpg",
      "assets/Emerson Park - Nelmes Road - After 9.jpg",
      "assets/Emerson Park - Nelmes Road - After 10.jpg",
      "assets/Emerson Park - Nelmes Road - After 11.jpg",
      "assets/Emerson Park - Nelmes Road - After 12.jpg",
      "assets/Emerson Park - Nelmes Road - After 13.jpg",
      "assets/Emerson Park - Nelmes Road - After 14.jpg",
      "assets/Emerson Park - Nelmes Road - After 15.jpg",
      "assets/Emerson Park - Nelmes Road - After 16.jpg",
      "assets/Emerson Park - Nelmes Road - After 17.jpg",
      "assets/Emerson Park - Nelmes Road - After 18.jpg",
    ]
  },
  { t: "Emerson Park — Sylvan Avenue", s: "Refurbishment · Emerson Park · London", tag: "Refurbishment", cls: "wide", label: "EMERSON PARK — SYLVAN AVENUE",
    slug: "Emerson-Park-Sylvan-Avenue",
    img: "assets/EP/Sylvan - Hero.jpg",
    duration: "8–9 months", year: "2026",
    brief: "A full refurbishment back to brick of a substantial family home on Sylvan Avenue, Emerson Park — including a single-storey extension, balcony formation, and the construction of an outdoor swimming pool and outbuilding. Six bedrooms, eight bathrooms across 600 sq m. A turnkey project.",
    approach: "We helped our client source the original house and then designed the scheme and obtained planning approval using our in-house architects and structural engineers — carrying the project from acquisition through design and planning to construction under one roof.",
    scope: ["Full refurbishment back to brick", "Single-storey extension", "Balcony formation", "Outdoor swimming pool", "Outbuilding construction", "Architectural & structural design"],
    video: "assets/EP/Sylvan - Walkthrough.mp4", videoPortrait: true,
    videoEyebrow: "Walkthrough", videoHeading: "Inside the build.",
    gallery: [
      "assets/EP/Sylvan - Hero.jpg",
      "assets/EP/Sylvan - After 1.jpg",
      "assets/EP/Sylvan - After 2.jpg",
      "assets/EP/Sylvan - After 3.jpg",
      "assets/EP/Sylvan - After 4.jpg",
      "assets/EP/Sylvan - After 5.jpg",
      "assets/EP/Sylvan - After 6.jpg",
    ],
    before: [
      "assets/EP/Sylvan - Before 1.jpg",
      "assets/EP/Sylvan - Before 2.jpg",
      "assets/EP/Sylvan - Before 3.jpg",
      "assets/EP/Sylvan - Before 4.jpg",
      "assets/EP/Sylvan - Before 5.jpg",
      "assets/EP/Sylvan - Before 6.jpg",
      "assets/EP/Sylvan - Before 7.jpg",
      "assets/EP/Sylvan - Before 8.jpg",
      "assets/EP/Sylvan - Before 9.jpg",
      "assets/EP/Sylvan - Before 10.jpg",
      "assets/EP/Sylvan - Before 11.jpg",
      "assets/EP/Sylvan - Before 12.jpg",
      "assets/EP/Sylvan - Before 13.jpg",
      "assets/EP/Sylvan - Before 14.jpg",
    ],
  },
  { hidden: true, t: "Hampstead House", s: "New build · 5 bed · NW3", tag: "New Build", cls: "tall", label: "HAMPSTEAD HOUSE",
    slug: "Hampstead-House",
    img: "assets/hampstead-house.jpg",
    budget: "£1.85m", duration: "14 months", year: "2024",
    brief: "A full new-build family home on a cleared plot in NW3 — five bedrooms, cinema room, landscaped garden and full smart-home integration.",
    challenge: "The client purchased a cleared brownfield plot with a complex ground condition report and strict Hampstead conservation area guidelines. Neighbours on three sides meant our programme and noise management had to be surgical. Every elevation required pre-approval from the local heritage officer before a brick was laid.",
    approach: "We appointed a conservation-specialist architect and coordinated a pre-application meeting with the planning authority before submitting. A concrete raft foundation resolved the ground-bearing issues in one pass. We maintained a daily neighbour communication log and delivered weekly video updates direct to the client — who was based in Dubai throughout the main build.",
    outcome: "Handed over four days ahead of the contracted date. The home achieved an EPC A rating, the smart-home system was installed and fully commissioned before the client flew in, and the landscaping was complete and mature enough to photograph on day one.",
    scope: ["New build construction", "Architectural & planning", "Interior design", "Smart home & AV", "Landscaping"],
    gallery: [
      "assets/hampstead-house.jpg",
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600210492493-0946911123ea?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1616137466211-f939a420be84?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=900&q=80&auto=format&fit=crop",
    ]
  },
  { hidden: true, t: "Islington Townhouse", s: "Refurbishment · Period home · N1", tag: "Refurbishment", cls: "wide", label: "ISLINGTON TOWNHOUSE",
    slug: "Islington-Townhouse",
    img: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=900&q=85&auto=format&fit=crop",
    budget: "£420k", duration: "7 months", year: "2023",
    brief: "Full gut refurbishment of a four-storey Victorian townhouse — structural alterations, new kitchen extension, and a complete interior overhaul.",
    challenge: "The property had been split into flats in the 1970s, leaving a tangle of compromised structural beams, mismatched service runs and several layers of floor build-up that had robbed the house of its original ceiling heights. The rear elevation also required a party-wall agreement with two adjoining owners before any excavation could begin.",
    approach: "We stripped the building back to its Victorian bones, engaged a structural engineer to redesign the beam layout, and negotiated both party-wall agreements within the first three weeks. The kitchen extension was designed as a contemporary zinc-roofed volume that reads as clearly modern yet respectful of the period facade — a balance the planning department commended.",
    outcome: "The finished house recovered an average of 180mm of ceiling height across all floors, the open-plan ground floor transformed the way the family lives, and the project was completed seven days early — allowing the family to move in before the school term began.",
    scope: ["Structural alterations", "Kitchen extension", "Full fit-out", "Plumbing & electrical", "Bespoke joinery"],
    gallery: [
      "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=900&q=85&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1615874959474-d609969a20ed?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600489000022-c2086d79f9d4?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600210491369-e753d80a41f3?w=900&q=80&auto=format&fit=crop",
    ]
  },
  { hidden: true, t: "Kensington Apartment", s: "Interior fit-out · 3 bed · W8", tag: "Interior", cls: "sqr", label: "KENSINGTON APARTMENT",
    slug: "Kensington-Apartment",
    img: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=900&q=85&auto=format&fit=crop",
    budget: "£290k", duration: "5 months", year: "2024",
    brief: "Luxury fit-out of a lateral apartment in W8 — bespoke joinery throughout, marble bathrooms, and a full Lutron lighting system.",
    challenge: "A lateral apartment across two original mansion-block floors presented a strict weight loading constraint for the stone flooring — each slab had to be individually assessed and signed off by the structural engineer. The building's listed status also meant all penetrations for the new Lutron wiring loom required listed-building consent.",
    approach: "We engaged a specialist stone consultant to specify a lighter-weight marble composite that met the load limits without compromising the visual intent. The Lutron infrastructure was routed entirely through existing service voids, leaving the original cornicing and plasterwork untouched. Every joinery item was designed in 3D and presented to the client for sign-off before workshop production began.",
    outcome: "The client described it as the most stress-free project they had experienced. The apartment was photographed for an interiors magazine within two weeks of completion, and the Lutron system has since been extended by the client to include the building's communal areas.",
    scope: ["Bespoke joinery", "Marble bathrooms", "Flooring & tiling", "Lutron lighting", "Decorating"],
    gallery: [
      "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=900&q=85&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600210492493-0946911123ea?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1583845112203-29329902332e?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=900&q=80&auto=format&fit=crop",
    ]
  },
  { hidden: true, t: "Richmond Mews", s: "Development · 6 units · TW9", tag: "Development", cls: "full", label: "RICHMOND MEWS",
    slug: "Richmond-Mews",
    img: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=1200&q=85&auto=format&fit=crop",
    budget: "£2.1m", duration: "18 months", year: "2023",
    brief: "A six-unit mews development from groundwork to handover — planning managed, all units sold off-plan before completion.",
    challenge: "The site had a complex title with an historic covenant restricting commercial use, and the local authority required a Section 106 agreement covering affordable housing contributions and a new pedestrian access. Utilities to the mews lane had never been formally adopted, adding an unexpected infrastructure element to the programme.",
    approach: "Our development consultancy team resolved the covenant issue with a title insurer before contracts exchanged, saving the client an estimated six weeks. We negotiated the S106 contribution down by demonstrating the viability impact, and project-managed the utility adoption in parallel with the main build to avoid any programme delay. All six units were marketed at first-fix stage with CGI walkthroughs produced by our in-house visualisation team.",
    outcome: "All six units sold off-plan at an average of 4% above the initial sales estimates. The development received a commendation from the local authority's design review panel, and two of the six buyers were referrals from the same scheme — the best measure of quality we know.",
    scope: ["Planning & development", "New build construction", "Interior design", "Landscaping", "Sales support"],
    gallery: [
      "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=1200&q=85&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1613977257363-707ba9348227?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=900&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=900&q=80&auto=format&fit=crop",
    ]
  },
];

const STEPS = [
  { n: "01", h: "Consultation", p: "We listen first. A relaxed conversation about your site, your ambitions, your budget and your timeline — with honest guidance from the very start." },
  { n: "02", h: "Design & Planning", p: "Architects, engineers and our team translate your brief into drawings and a planning strategy, with 3D visualisations so you can see it before we build it." },
  { n: "03", h: "Pre-Construction", p: "Fixed costings, programme, building-control sign-off and warranties locked in — so there are no surprises once the groundwork begins." },
  { n: "04", h: "Build", p: "A single managed team on site, with clear weekly communication and meticulous attention to detail at every stage of the build." },
  { n: "05", h: "Handover & Aftercare", p: "A thorough handover, your warranties in hand, and dedicated post-build support. We treat every project as if it were our own — long after completion." },
];

const TESTIMONIALS = [
  { q: "Chana Design and Build were exceptional from the very beginning. We initially found it challenging to secure the right plot for our project, but their team took that burden off our shoulders by liaising directly with estate agents, negotiating on our behalf, and assisting throughout the acquisition process. Once the plot was secured, they designed a bespoke home tailored perfectly to our requirements and delivered a build of outstanding quality. Hardeep was professional, attentive, and supportive throughout the entire journey, consistently going above and beyond our expectations. The project was completed on time, within budget, and to an exceptional standard. We would highly recommend Chana Design and Build to anyone looking for a trustworthy and experienced construction company.", nm: "Manickavagam Sritharan", rl: "New Build · Turnkey", stars: 5 },
  { q: "Finding the perfect location for your dream home can be a daunting experience, but Hardeep and the team at Chana Design and Build made the entire process seamless and stress-free. They helped us identify and secure the ideal plot before designing our home through their in-house architectural team. Having access to their in-house architects, structural engineers, and party wall specialists made the design, planning, and approval stages incredibly efficient. Throughout the project, the team demonstrated exceptional knowledge, professionalism, and honesty, always providing practical advice and guidance when needed. Their attention to detail, transparent communication, and commitment to delivering the best possible outcome gave us complete confidence from start to finish. I cannot recommend Chana Design and Build highly enough.", nm: "Mark Preston", rl: "New Build · Turnkey", stars: 5 },
  { q: "We are currently working with Chana Design and Build on a substantial refurbishment project at our 6,000 sq ft property in Emerson Park, Hornchurch, which includes the installation of an outdoor swimming pool. Having been recommended to us by a friend whose new-build project they successfully completed, our expectations were already high. However, the team has exceeded them in every respect. Their efficiency, meticulous workmanship, and excellent communication have been outstanding throughout the project. A project of this scale can often be stressful, but Chana Design and Build have made the entire experience enjoyable and rewarding. Remarkably, the project is currently ahead of schedule — something rarely seen in the construction industry. We would not hesitate to use them again and wholeheartedly recommend them to anyone considering a construction or refurbishment project.", nm: "Thanalingam Iyinkaran", rl: "Refurbishment · Emerson Park", stars: 5 },
];

const VALUES = [
  { icon: "◈", h: "Craftsmanship", p: "Every detail matters. We hold ourselves to a standard most companies talk about but few actually deliver." },
  { icon: "◈", h: "Transparency", p: "Fixed costs, honest timelines and open communication from day one through to long after handover." },
  { icon: "◈", h: "Family Values", p: "We treat every client's home as if it were our own — with the care, pride and attention it deserves." },
  { icon: "◈", h: "Excellence", p: "We work only with the best tradespeople, materials and suppliers. There is no shortcut that is worth taking." },
  { icon: "◈", h: "Progressive", p: "Embracing smart home technology, sustainable methods and modern construction techniques on every project." },
  { icon: "◈", h: "Aftercare", p: "Our relationship does not end at handover. Dedicated post-build support and warranties you can count on." },
];

const TRADES = [
  { cat: "Structure & Shell", items: ["New build construction", "Extensions & additions", "Loft conversions", "Basement excavation", "Structural alterations"] },
  { cat: "Fit-out & Finish", items: ["Kitchen & bathroom fitting", "Flooring & tiling", "Plastering & rendering", "Joinery & bespoke carpentry", "Painting & decorating"] },
  { cat: "Mechanical & Electrical", items: ["Plumbing & heating", "Electrical installation", "Underfloor heating", "Air conditioning", "Smart home & home automation"] },
  { cat: "Security & Technology", items: ["CCTV & alarm systems", "Access control", "AV & home cinema", "EV charging points", "Solar & renewables"] },
];

const PROJECTS_ALL = PROJECTS;
const PROJECTS_VISIBLE = PROJECTS.filter(p => !p.hidden);
Object.assign(window, { NAV_LINKS, ACCREDS, SERVICES, STATS, PROJECTS: PROJECTS_VISIBLE, PROJECTS_ALL, STEPS, TESTIMONIALS, VALUES, TRADES });
